# Generated by Django 4.0.5 on 2022-07-05 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.ForeignKey(choices=[('Trainings', 'Trainings'), ('Yoga', 'Yoga'), ('Workouts', 'Workouts'), ('Diet', 'Diet'), ('Bootcamp', 'Bootcamp'), ('Tournament', 'Tournament')], on_delete=django.db.models.deletion.CASCADE, to='services.category'),
        ),
    ]
