# Generated by Django 4.0.5 on 2022-07-05 09:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_services_image_alter_services_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='video'),
        ),
    ]
