# Generated by Django 4.0.5 on 2022-07-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_services_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('Trainings', 'Trainings'), ('Yoga', 'Yoga'), ('Workouts', 'Workouts'), ('Diet', 'Diet'), ('Bootcamp', 'Bootcamp'), ('Tournament', 'Tournament')], max_length=50, null=True),
        ),
    ]
