# Generated by Django 4.0.5 on 2022-07-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_services_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='video',
        ),
    ]
